limit_warc_files = 5
host_graph_base_path = "data/webgraph"
page_graph_base_path = "data/webgraph_page"
batch_size = 1

[warc_source]
type = "HTTP"
base_url = "https://data.commoncrawl.org/"
warc_paths_file = "data/warc.paths"
