limit_warc_files = 4
graph_base_path = "data/webgraph"
batch_size = 2

[warc_source]
type = "HTTP"
base_url = "https://data.commoncrawl.org/"
warc_paths_file = "warc.paths"
# type = "Local"
# folder = "./data/warc_files"
# names = ["CC-MAIN-20220116093137-20220116123137-00049.warc.gz"]