[package]
name = "cuely"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
authors = ['Cuely ApS. <hello@cuely.io>']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cuely"

[dependencies]
bincode = "1.3.3"
clap = { version = "3.1.18", features = ["derive"] }
encoding_rs = "0.8.31"
flate2 = "1.0.23"
indicatif = { version = "0.16.2", features = ["rayon"] }
itertools = "0.10.3"
lru = "0.7.6"
rand = "0.8.5"
rayon = "1.5.3"
reqwest = { version = "0.11.10", features = ["blocking"] }
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"
serde = "1.0.137"
serde_json = "1.0.81"
sled = { version = "0.34.7", features = ["compression"] }
tantivy = "0.18.0"
thiserror = "1.0.31"
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
whatlang = "0.16.0"
tokio = { version = "1.19.2", features = ["full"] }
askama = "0.11.1"
axum = "0.5.9"
anyhow = "1.0.58"
axum-extra = { version = "0.3.4", features = ["spa"] }
html-escape = "0.2.11"
logos = "0.12.1"
csv = "1.1.6"
fst = { version = "0.4.7", features = ["levenshtein"] }
lazy_static = "1.4.0"
rocksdb = "0.18.0"
image = "0.24.3"
chrono = "0.4.20"
uuid = "1.1.2"
futures = "0.3.21"
quick-xml = "0.23.0"
bzip2 = "0.4.3"
parse_wiki_text = "0.1.5"
md5 = "0.7.0"
memmap = "0.7.0"
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
once_cell = "1.13.1"
regex = "1.6.0"

[dev-dependencies]
maplit = "1.0.2"

[profile.release]
debug = true

[build-dependencies]
lalrpop = "0.19.8"
