[workspace]
members = [
    "core",
    "optics"
]

[profile.release]
debug = true
lto = "thin"

[workspace.dependencies]
bincode = "1.3.3"
clap = { version = "3.1.18", features = ["derive"] }
encoding_rs = "0.8.31"
flate2 = "1.0.23"
indicatif = { version = "0.16.2", features = ["rayon"] }
itertools = "0.10.3"
rayon = "1.5.3"
reqwest = { version = "0.11.10", features = ["blocking", "stream"] }
serde = { version = "1.0.137", features = ["rc", "derive"] }
serde_json = "1.0.81"
tantivy = { git = "https://github.com/quickwit-oss/tantivy.git", rev = "5d4535de83d214765c29501f0418f1ff38a607b1" }
thiserror = "1.0.31"
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
whatlang = "0.16.0"
tokio = { version = "1.23.1", features = ["full"] }
askama = "0.11.1"
axum = "0.6.9"
axum-extra = { version = "0.6.0", features = ["spa"] }
axum-macros = "0.3.4"
anyhow = "1.0.58"
html-escape = "0.2.11"
logos = "0.12.1"
csv = "1.1.6"
fst = { version = "0.4.7", features = ["levenshtein"] }
rocksdb = "0.19.0"
image = "0.24.3"
chrono = {version = "0.4.23", features = ["serde"] }
uuid = "1.1.2"
futures = "0.3.21"
quick-xml = "0.23.0"
bzip2 = "0.4.4"
parse_wiki_text = "0.1.5"
md5 = "0.7.0"
memmap = "0.7.0"
once_cell = "1.13.1"
regex = "1.6.0"
http = "0.2.8"
kuchiki = "0.8.1"
tower-http = { version = "0.4.0", features = ["compression-gzip"] }
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
lalrpop = { version = "0.19.8", features = ["lexer"] }
serde_urlencoded = "0.7.1"
rust-stemmers = "1.2.0"
min-max-heap = "1.3.0"
base64 = "0.13.0"
async-trait = "0.1.57"
urlencoding = "2.1.2"
bitvec = "1.0.1"
criterion = "0.3.6"
maplit = "1.0.2"
rand = "0.8.5"
crossbeam-channel = "0.5.6"
num_cpus = "1.15.0"
onnxruntime = { git = "https://github.com/StractOrg/onnxruntime-rs" }
tokenizers = "0.13.2"
byteorder = "1.4.3"
async-stream = "0.3.3"
tokio-stream = "0.1.11"
scylla = "0.7.0"
chitchat = "0.5.0"