[package]
name = "cuely"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cuely"

[dependencies]
bincode = "1.3.3"
encoding_rs = "0.8.31"
flate2 = "1.0.23"
futures = "0.3.21"
indicatif = "0.16.2"
itertools = "0.10.3"
nom = "7.1.1"
reqwest = "0.11.10"
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"
scraper = "0.13.0"
serde = "1.0.137"
sled = { version = "0.34.7", features = ["compression"] }
tantivy = "0.18.0"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
toml = "0.5.9"
