[package]
name = "cuely"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
authors = ['Cuely ApS. <hello@cuely.io>']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cuely"

[dependencies]
bincode = "1.3.3"
clap = { version = "3.1.18", features = ["derive"] }
encoding_rs = "0.8.31"
flate2 = "1.0.23"
htmlescape = "0.3.1"
indicatif = { version = "0.16.2", features = ["rayon"] }
itertools = "0.10.3"
lru = "0.7.6"
nom = "7.1.1"
rand = "0.8.5"
rayon = "1.5.3"
reqwest = { version = "0.11.10", features = ["blocking"] }
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"
scraper = "0.13.0"
serde = "1.0.137"
serde_json = "1.0.81"
sled = { version = "0.34.7", features = ["compression"] }
tantivy = "0.18.0"
thiserror = "1.0.31"
tl = "0.7.5"
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
whatlang = "0.16.0"
tokio = { version = "1.19.2", features = ["full"] }
askama = "0.11.1"
axum = "0.5.9"
anyhow = "1.0.58"

[dev-dependencies]
maplit = "1.0.2"

[profile.release]
debug = true
