[package]
name = "stract-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
distributed.workspace = true
rust-s3.workspace = true
serde.workspace = true
