[package]
name = "warc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono.workspace = true
encoding_rs = "0.8.33"
flate2.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
proptest-derive.workspace = true
