num_workers = 10
politeness_factor = 1.0
timeout_seconds = 30
coordinator_host = "0.0.0.0:8080"

[user_agent]
token = "StractSearch"
full = "Mozilla/5.0 (compatible; StractSearch/0.1; +https://trystract.com/webmasters)"

[s3]
bucket = "crawl"
folder = "test1"
access_key = "<access_key>"
secret_key = "<secret_key>"
endpoint = "https://s3.trystract.com"