[general]
# Directories to search for templates, relative to the crate root.
dirs = ["../frontend/dist/"]
# Unless you add a `-` in a block, whitespace characters won't be trimmed.
whitespace = "preserve"
