warc_paths_file = "warc.paths"
centrality_store_path = "./data/centrality/host"
limit_warc_files = 1
download_images = false

[warc_source]
# type = "Local"
# folder = "./data/warc_files"
# names = ["CC-MAIN-20220116093137-20220116123137-00049.warc.gz"]
type = "HTTP"
base_url = "https://data.commoncrawl.org/"
warc_paths_file = "warc.paths"
