centrality_store_path = "./data/centrality"
limit_warc_files = 1
download_images = false
minimum_clean_words = 40
# crawl_stability_path = "data/crawl-stability"

[warc_source]
type = "Local"
folder = "./data"
names = ["sample.warc.gz"]
# type = "HTTP"
# base_url = "https://data.commoncrawl.org/"
# warc_paths_file = "warc.paths"
