warc_paths_file = "warc.paths"
centrality_store_path = "./data/centrality"
limit_warc_files = 40
download_images = false
batch_size = 5

[warc_source]
# type = "Local"
# folder = "./data/warc_files"
# names = ["CC-MAIN-20220116093137-20220116123137-00049.warc.gz", "CC-MAIN-20220116093137-20220116123137-00049_1.warc.gz", "CC-MAIN-20220116093137-20220116123137-00049_2.warc.gz"]
type = "HTTP"
base_url = "https://data.commoncrawl.org/"
warc_paths_file = "warc.paths"
