host_centrality_store_path = "./data/centrality"
limit_warc_files = 20
# minimum_clean_words = 40

[warc_source]
base_url = "https://data.commoncrawl.org/"
folder = "./data"
names = ["sample.warc.gz"]
type = "Local"
type = "HTTP"
warc_paths_file = "data/warc.paths"
