type = "Indexer"
mode = "Master"

limit_warc_files = 100
workers = ["0.0.0.0:1337", "0.0.0.0:1338", "0.0.0.0:1339", "0.0.0.0:1340", "0.0.0.0:1341", "0.0.0.0:1342", "0.0.0.0:1343"]

[warc_source]
type = "HTTP"
base_url = "https://data.commoncrawl.org/"
warc_paths_file = "warc.paths"