[package]
name = "webpage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bincode.workspace = true
chrono.workspace = true
csv.workspace = true
itertools.workspace = true
kuchiki.workspace = true
naive_bayes.workspace = true
once_cell.workspace = true
publicsuffix.workspace = true
regex.workspace = true
rust-stemmers = "1.2.0"
schema.workspace = true
serde.workspace = true
serde_json.workspace = true
simhash.workspace = true
stdx.workspace = true
tantivy.workspace = true
thiserror.workspace = true
tokenizer.workspace = true
tracing.workspace = true
url.workspace = true
utoipa.workspace = true
webgraph.workspace = true
whatlang.workspace = true

[dev-dependencies]
maplit.workspace = true
