[package]
name = "ggml-sys"
authors = ['Stract <hello@stract.com>']
version = "0.1.0"
edition = "2021"
license = "MIT"

[build-dependencies]
bindgen = { workspace = true }
cmake = { workspace = true }
cc = { workspace = true }
