cluster_id = "dev_alice"
gossip_addr = "0.0.0.0:3008"
host = "0.0.0.0:3004"
gossip_seed_nodes = ["0.0.0.0:3005", "0.0.0.0:3006"]
alice_path = "data/alice"
encryption_key = "URyJQTjwUjTq6FSRoZGdbUdTIvqs/QxkPacQio8Lhxc=" # don't use this key for anything important

[accelerator]
layer_fraction = 1.0
quantize_fraction = 0.0 # percentage of layers on accelerator to quantize

[accelerator.device]
type = "mps"

[accelerator.dtype]
type = "float"
