cluster_id = "dev_api"
crossencoder_model_path = "data/cross_encoder"
gossip_addr = "0.0.0.0:3005"
gossip_seed_nodes = ["0.0.0.0:3006", "0.0.0.0:3007"]
host = "0.0.0.0:3000"
# lambda_model_path = "data/lambdamart.txt"
prometheus_host = "0.0.0.0:3001"
queries_csv_path = "data/queries_us.csv"
spell_checker_path = "data/web_spell/checker"
bangs_path = "data/bangs.json"
summarizer_path = "data/summarizer"

[thresholds]
entity_sidebar = 0.0
stackoverflow = 0.0

[widgets]
thesaurus_paths = ["data/english-wordnet-2022-subset.ttl"]

[correction_config]
correction_threshold = 3.0
lm_prob_weight = 1.0

[llm]
api_base= "http://localhost:4000/v1"
model = "data/mistral-7b-instruct-v0.2.Q4_K_M.gguf"
# model = "TheBloke/Mistral-7B-Instruct-v0.2-AWQ"
# model = "mistralai/Mixtral-8x7B-Instruct-v0.1"
