cluster_id = "dev_frontend"
queries_csv_path = "data/queries_us.csv"
host = "0.0.0.0:3000"
prometheus_host = "0.0.0.0:3001"
gossip_addr = "0.0.0.0:3004"
gossip_seed_nodes = ["0.0.0.0:3005", "0.0.0.0:3006"]
crossencoder_model_path = "data/cross_encoder"
# lambda_model_path = "data/lambdamart.txt"
# qa_model_path = "data/qa_model"
bangs_path = "data/bangs.json"
summarizer_path = "data/summarizer"