queries_csv_path = "data/queries_us.csv"
host = "0.0.0.0:3000"
prometheus_host = "0.0.0.0:3001"
search_servers = [["0.0.0.0:3002"]]
crossencoder_model_path = "data/cross_encoder"
# qa_model_path = "data/qa_model"
bangs_path = "data/bangs.json"
summarizer_path = "data/summarizer"