cluster_id = "dev_search"
entity_index_path = "data/entity"
gossip_addr = "0.0.0.0:3006"
gossip_seed_nodes = ["0.0.0.0:3005"]
host = "0.0.0.0:3002"
host_centrality_store_path = "data/centrality"
index_path = "data/index"
shard_id = 0
# linear_model_path = "data/linear_model.json"
lambda_model_path = "data/lambdamart.txt"

[snippet]
max_considered_words = 10_000
num_words_for_lang_detection = 1_000
