type = "Webgraph"
mode = "Master"

warc_paths_file = "warc.paths"
addr = "0.0.0.0:1337"
workers = ["0.0.0.0:1338"]


# [warc_source]
# type = "S3"
# name = "us-east-1"
# endpoint = "https://s3.us-east-1.amazonaws.com"
# bucket = "commoncrawl"

[warc_source]
type = "HTTP"
base_url = "https://data.commoncrawl.org/"
