no-clearly-defined = true
private = { ignore = true }

accepted = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "ISC",
    "CC0-1.0",
    "Unicode-DFS-2016",
    "OpenSSL",
    "Zlib",
    "WTFPL",
    "Unlicense",
    "zlib-acknowledgement",
    "GPL-3.0",              # aglpv3 software can link glpv3 libraries under section 13 of gplv3
    "BSL-1.0",
    "AGPL-3.0",
]

workarounds = ["ring"]

[stract]
accepted = ["AGPL-3.0"]

[client-wasm]
accepted = ["AGPL-3.0"]

[wav]
accepted = ["LGPL-3.0"]
