[package]
edition = "2021"
name = "zimba"
version = "0.1.0"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lzma = {workspace = true}
memmap2 = {workspace = true}
thiserror = {workspace = true}
zstd = {workspace = true}
